using Microsoft.Xna.Framework.Audio;
using Microsoft.Xna.Framework.Content;

namespace com.robotacid.sound
{
    /// <summary>
    /// Embeds for all sounds. Also loads them into the SoundManager.
	/// 
	/// @author Aaron Steed, robotacid.com
	/// @conversion Paul Cunningham, pumpkin-games.net
    /// </summary>
    public class SoundLibrary {

		private static SoundEffect BitBlastRattleSound;
		private static SoundEffect TrapTwangSound1;
		private static SoundEffect TrapTwangSound2;
		private static SoundEffect TrapTwangSound3;
		private static SoundEffect TrapTwangSound4;
		private static SoundEffect RattleKillSound1;
		private static SoundEffect RattleKillSound2;
		private static SoundEffect RattleKillSound3;
		private static SoundEffect RattleKillSound4;
		private static SoundEffect AdventureSound1;
		private static SoundEffect AdventureSound2;
		private static SoundEffect AdventureSound3;
		private static SoundEffect AdventureSound4;
		private static SoundEffect BassyKillSound1;
		private static SoundEffect BassyKillSound2;
		private static SoundEffect BassyKillSound3;
		private static SoundEffect BassyKillSound4;
		private static SoundEffect MoverKillSound1;
		private static SoundEffect MoverKillSound2;
		private static SoundEffect MoverKillSound3;
		private static SoundEffect MoverKillSound4;
		private static SoundEffect AllySound1;
		private static SoundEffect AllySound2;
		private static SoundEffect AllySound3;
		private static SoundEffect AllySound4;
		private static SoundEffect MeatyKillSound1;
		private static SoundEffect MeatyKillSound2;
		private static SoundEffect MeatyKillSound3;
		private static SoundEffect MeatyKillSound4;
		private static SoundEffect BlockedSound1;
		private static SoundEffect BlockedSound2;
		private static SoundEffect BlockedSound3;
		private static SoundEffect BlockedSound4;
		private static SoundEffect BuzzRattleSound;
		private static SoundEffect ChirupSound;
		private static SoundEffect DeathSound1;
		private static SoundEffect DeathSound2;
		private static SoundEffect DeathSound3;
		private static SoundEffect DeathSound4;
		private static SoundEffect DoorSound1;
		private static SoundEffect DoorSound2;
		private static SoundEffect DoorSound3;
		private static SoundEffect DoorSound4;
		private static SoundEffect EndingSound1;
		private static SoundEffect EndingSound2;
		private static SoundEffect EndingSound3;
		private static SoundEffect EndingSound4;
		private static SoundEffect GeneratorSound1;
		private static SoundEffect GeneratorSound2;
		private static SoundEffect GeneratorSound3;
		private static SoundEffect GeneratorSound4;
		private static SoundEffect HitRattleSound;
		private static SoundEffect PunchRattleSound;
		private static SoundEffect PushSound1;
		private static SoundEffect PushSound2;
		private static SoundEffect PushSound3;
		private static SoundEffect PushSound4;
		private static SoundEffect RattleSound1;
		private static SoundEffect RattleSound2;
		private static SoundEffect SlideSound;
		private static SoundEffect StepSound1;
		private static SoundEffect StepSound2;
		private static SoundEffect StepSound3;
		private static SoundEffect StrangeExchangeSound;
		private static SoundEffect TwangKillSound;
		private static SoundEffect TwangMoveSound;
		private static SoundEffect EndSound1;
		private static SoundEffect EndSound2;
		private static SoundEffect EndSound3;
		private static SoundEffect EndSound4;

        public static void LoadContent(ContentManager content) {
 
		    BitBlastRattleSound = content.Load<SoundEffect>("sound/8bit-blast-rattle");
		    TrapTwangSound1 = content.Load<SoundEffect>("sound/trapTwang1");
		    TrapTwangSound2 = content.Load<SoundEffect>("sound/trapTwang2");
		    TrapTwangSound3 = content.Load<SoundEffect>("sound/trapTwang3");
		    TrapTwangSound4 = content.Load<SoundEffect>("sound/trapTwang4");
		    RattleKillSound1 = content.Load<SoundEffect>("sound/rattleKill1");
		    RattleKillSound2 = content.Load<SoundEffect>("sound/rattleKill2");
		    RattleKillSound3 = content.Load<SoundEffect>("sound/rattleKill3");
		    RattleKillSound4 = content.Load<SoundEffect>("sound/rattleKill4");
		    AdventureSound1 = content.Load<SoundEffect>("sound/adventure1");
		    AdventureSound2 = content.Load<SoundEffect>("sound/adventure2");
		    AdventureSound3 = content.Load<SoundEffect>("sound/adventure3");
		    AdventureSound4 = content.Load<SoundEffect>("sound/adventure4");
		    BassyKillSound1 = content.Load<SoundEffect>("sound/bassy-kill1");
		    BassyKillSound2 = content.Load<SoundEffect>("sound/bassy-kill2");
		    BassyKillSound3 = content.Load<SoundEffect>("sound/bassy-kill3");
		    BassyKillSound4 = content.Load<SoundEffect>("sound/bassy-kill4");
		    MoverKillSound1 = content.Load<SoundEffect>("sound/moverKill1");
		    MoverKillSound2 = content.Load<SoundEffect>("sound/moverKill2");
		    MoverKillSound3 = content.Load<SoundEffect>("sound/moverKill3");
		    MoverKillSound4 = content.Load<SoundEffect>("sound/moverKill4");
		    AllySound1 = content.Load<SoundEffect>("sound/ally1");
		    AllySound2 = content.Load<SoundEffect>("sound/ally2");
		    AllySound3 = content.Load<SoundEffect>("sound/ally3");
		    AllySound4 = content.Load<SoundEffect>("sound/ally4");
		    MeatyKillSound1 = content.Load<SoundEffect>("sound/meatyKill1");
		    MeatyKillSound2 = content.Load<SoundEffect>("sound/meatyKill2");
		    MeatyKillSound3 = content.Load<SoundEffect>("sound/meatyKill3");
		    MeatyKillSound4 = content.Load<SoundEffect>("sound/meatyKill4");
		    BlockedSound1 = content.Load<SoundEffect>("sound/blocked1");
		    BlockedSound2 = content.Load<SoundEffect>("sound/blocked2");
		    BlockedSound3 = content.Load<SoundEffect>("sound/blocked3");
		    BlockedSound4 = content.Load<SoundEffect>("sound/blocked4");
		    BuzzRattleSound = content.Load<SoundEffect>("sound/buzz-rattle");
		    ChirupSound = content.Load<SoundEffect>("sound/chirup");
		    DeathSound1 = content.Load<SoundEffect>("sound/death1");
		    DeathSound2 = content.Load<SoundEffect>("sound/death2");
		    DeathSound3 = content.Load<SoundEffect>("sound/death3");
		    DeathSound4 = content.Load<SoundEffect>("sound/death4");
		    DoorSound1 = content.Load<SoundEffect>("sound/door1");
		    DoorSound2 = content.Load<SoundEffect>("sound/door2");
		    DoorSound3 = content.Load<SoundEffect>("sound/door3");
		    DoorSound4 = content.Load<SoundEffect>("sound/door4");
		    EndingSound1 = content.Load<SoundEffect>("sound/ending1");
		    EndingSound2 = content.Load<SoundEffect>("sound/ending2");
		    EndingSound3 = content.Load<SoundEffect>("sound/ending3");
		    EndingSound4 = content.Load<SoundEffect>("sound/ending4");
		    GeneratorSound1 = content.Load<SoundEffect>("sound/generator1");
		    GeneratorSound2 = content.Load<SoundEffect>("sound/generator2");
		    GeneratorSound3 = content.Load<SoundEffect>("sound/generator3");
		    GeneratorSound4 = content.Load<SoundEffect>("sound/generator4");
		    HitRattleSound = content.Load<SoundEffect>("sound/hit-rattle");
		    PunchRattleSound = content.Load<SoundEffect>("sound/punch-rattle");
		    PushSound1 = content.Load<SoundEffect>("sound/push1");
		    PushSound2 = content.Load<SoundEffect>("sound/push2");
		    PushSound3 = content.Load<SoundEffect>("sound/push3");
		    PushSound4 = content.Load<SoundEffect>("sound/push4");
		    RattleSound1 = content.Load<SoundEffect>("sound/rattle1");
		    RattleSound2 = content.Load<SoundEffect>("sound/rattle2");
		    SlideSound = content.Load<SoundEffect>("sound/slide");
		    StepSound1 = content.Load<SoundEffect>("sound/step1");
		    StepSound2 = content.Load<SoundEffect>("sound/step2");
		    StepSound3 = content.Load<SoundEffect>("sound/step3");
		    StrangeExchangeSound = content.Load<SoundEffect>("sound/strange-exchange");
		    TwangKillSound = content.Load<SoundEffect>("sound/twang-kill");
		    TwangMoveSound = content.Load<SoundEffect>("sound/twang-move");
		    EndSound1 = content.Load<SoundEffect>("sound/end1");
		    EndSound2 = content.Load<SoundEffect>("sound/end2");
		    EndSound3 = content.Load<SoundEffect>("sound/end3");
		    EndSound4 = content.Load<SoundEffect>("sound/end4");
        }

        public static void init() {
            SoundManager.addSound(BitBlastRattleSound, "bitBlastRattle", 0.5);
			SoundManager.addSound(TrapTwangSound1, "trapTwang1", 0.8);
			SoundManager.addSound(TrapTwangSound2, "trapTwang2", 0.8);
			SoundManager.addSound(TrapTwangSound3, "trapTwang3", 0.8);
			SoundManager.addSound(TrapTwangSound4, "trapTwang4", 0.8);
			SoundManager.addSound(RattleKillSound1, "rattleKill1", 0.8);
			SoundManager.addSound(RattleKillSound2, "rattleKill2", 0.8);
			SoundManager.addSound(RattleKillSound3, "rattleKill3", 0.8);
			SoundManager.addSound(RattleKillSound4, "rattleKill4", 0.8);
			SoundManager.addSound(AdventureSound1, "adventure1", 0.6);
			SoundManager.addSound(AdventureSound2, "adventure2", 0.6);
			SoundManager.addSound(AdventureSound3, "adventure3", 0.6);
			SoundManager.addSound(AdventureSound4, "adventure4", 0.6);
			SoundManager.addSound(BassyKillSound1, "bassyKill1", 0.3);
			SoundManager.addSound(BassyKillSound2, "bassyKill2", 0.3);
			SoundManager.addSound(BassyKillSound3, "bassyKill3", 0.3);
			SoundManager.addSound(BassyKillSound4, "bassyKill4", 0.3);
			SoundManager.addSound(MoverKillSound1, "moverKill1", 0.8);
			SoundManager.addSound(MoverKillSound2, "moverKill2", 0.8);
			SoundManager.addSound(MoverKillSound3, "moverKill3", 0.8);
			SoundManager.addSound(MoverKillSound4, "moverKill4", 0.8);
			SoundManager.addSound(AllySound1, "ally1", 1.0);
			SoundManager.addSound(AllySound2, "ally2", 1.0);
			SoundManager.addSound(AllySound3, "ally3", 1.0);
			SoundManager.addSound(AllySound4, "ally4", 1.0);
			SoundManager.addSound(MeatyKillSound1, "meatyKill1", 0.6);
			SoundManager.addSound(MeatyKillSound2, "meatyKill2", 0.6);
			SoundManager.addSound(MeatyKillSound3, "meatyKill3", 0.6);
			SoundManager.addSound(MeatyKillSound4, "meatyKill4", 0.6);
			SoundManager.addSound(BlockedSound1, "blocked1", 0.6);
			SoundManager.addSound(BlockedSound2, "blocked2", 0.6);
			SoundManager.addSound(BlockedSound3, "blocked3", 0.6);
			SoundManager.addSound(BlockedSound4, "blocked4", 0.6);
			SoundManager.addSound(BuzzRattleSound, "buzzRattle", 1.0);
			SoundManager.addSound(ChirupSound, "chirup", 0.15);
			SoundManager.addSound(DeathSound1, "death1", 0.5);
			SoundManager.addSound(DeathSound2, "death2", 0.5);
			SoundManager.addSound(DeathSound3, "death3", 0.5);
			SoundManager.addSound(DeathSound4, "death4", 0.5);
			SoundManager.addSound(DoorSound1, "door1", 0.8);
			SoundManager.addSound(DoorSound2, "door2", 0.8);
			SoundManager.addSound(DoorSound3, "door3", 0.5);
			SoundManager.addSound(DoorSound4, "door4", 0.8);
			SoundManager.addSound(EndingSound1, "ending1", 0.3);
			SoundManager.addSound(EndingSound2, "ending2", 0.3);
			SoundManager.addSound(EndingSound3, "ending3", 0.3);
			SoundManager.addSound(EndingSound4, "ending4", 0.3);
			SoundManager.addSound(GeneratorSound1, "generator1", 0.5);
			SoundManager.addSound(GeneratorSound2, "generator2", 0.5);
			SoundManager.addSound(GeneratorSound3, "generator3", 0.5);
			SoundManager.addSound(GeneratorSound4, "generator4", 0.5);
			SoundManager.addSound(HitRattleSound, "hitRattle", 0.5);
			SoundManager.addSound(PunchRattleSound, "punchRattle", 0.6);
			SoundManager.addSound(PushSound1, "push1", 0.8);
			SoundManager.addSound(PushSound2, "push2", 0.8);
			SoundManager.addSound(PushSound3, "push3", 0.8);
			SoundManager.addSound(PushSound4, "push4", 0.8);
			SoundManager.addSound(RattleSound1, "rattle1", 0.7);
			SoundManager.addSound(RattleSound2, "rattle2", 0.7);
			SoundManager.addSound(SlideSound, "slide", 0.3);
			SoundManager.addSound(StepSound1, "step1", 0.5);
			SoundManager.addSound(StepSound2, "step2", 0.5);
			SoundManager.addSound(StepSound3, "step3", 0.5);
			SoundManager.addSound(StrangeExchangeSound, "strangeExchange", 0.5);
			SoundManager.addSound(TwangKillSound, "twangKill", 0.3);
			SoundManager.addSound(TwangMoveSound, "twangMove", 0.3);
			SoundManager.addSound(EndSound1, "end1", 1.0);
			SoundManager.addSound(EndSound2, "end2", 1.0);
			SoundManager.addSound(EndSound3, "end3", 1.0);
			SoundManager.addSound(EndSound4, "end4", 1.0);
        }
    }
}
